### ISSUE TITLE
Unable to install using instructions.  404 errors/etc.

### ISSUE THREAD

**Issue by Nazosan** [kshetline/aw-clock#29]
I wasn't able to catch all the errors when running sudo ./build.sh since it doesn't seem to want to pipe to a log and I have to just go with what fits in my scrollback, but I'm catching some 404 errors in the process.  In particular, there's an error almost right off for node-sass where it just doesn't even find the url "https://github.com/sass/node-sass/releases/download/v4.14.1/linux-arm-72_binding.node" at all.  When I look in their official releases page manually I don't even see any official ARM releases at all for any version, so maybe they've removed their ARM support?

Is there a way I can save a log of the process?  Something like "sudo ./build.sh --ddev > ./build.log" doesn't work.

**Comment by kshetline** [comment]
Sorry I didn't notice your issue sooner.

I've just tried to reproduce your bug, starting from a fresh install (not so fresh that Node.js had to be installed from scratch, but fresh otherwise) on my Raspberry Pi. I saw the 404 error go by, but the install continued without a problem (very slowly, but it worked).

node-sass has a very long and complicated build process, and I don't know all the ins and outs of it, but even with all the errors and warning that go by, it works for me, so it's hard to guess what problem you might be having with it.

What you can do to better catch and log any errors is manually perform a couple of the steps that build.sh does for you, namely the initial node modules installations.

1. Start with a fresh clone of the project.
2. `cd aw-clock/server`
3. `npm i`
4. The above sets up the server part of the project, and should go smoothly, since node-sass isn't needed by the server.
5. `cd ..` _(get back to the root directory)_
6. `npm i &> npm.log`

**Comment by kshetline** [comment]
Given a lack of response, and not being able to reproduce this issue, I'm closing it for now.
