### ISSUE TITLE
disabling kiosk

### ISSUE THREAD

**Issue by pidloop** [kshetline/aw-clock#70]
How do I disable automatically starting in kiosk mode upon boot?

I tried setting AWC_KIOSK_MODE=false in /etc/default/weatherService then rebooting but no change, it still comes up.

BTW, the project README.md file says this file is named /etc/defaults/weatherService

**Comment by kshetline** [comment]
For the case of the kiosk mode, the setting in the config file only serves to keep the state you last used when running the interactive setup, so that if you run `sudo ./build.sh -i` again, your setting will be remembered.

If you want to turn off kiosk mode without going through set up again, you can edit the file `/home/pi/.config/lxsession/LXDE-pi/autostart`, and remove the `--kiosk` parameter from the `chromium-browser` command.

**Comment by pidloop** [comment]
Works. Thanks,
